version: "3.7"
services:
  # target node
  centos7:
    build:
      context: ./nodes/centos7
      dockerfile: Dockerfile
    privileged: true
    command: /sbin/init
    image: centos7
    container_name: centos7
    hostname: centos7
    tty: true
    volumes:
      - ./workspace:/home/ansible/workspace
    working_dir: /home/ansible
  # ansible実行環境
  controller:
    build:
      context: ./controller
      dockerfile: Dockerfile
    image: controller
    container_name: controller
    hostname: controller
    tty: true
    volumes:
      - ./playbooks:/workspace
    working_dir: /workspace
