version: "3.7"
services:
  # target node
  centos7:
    build:
      context: ./nodes/centos7
      dockerfile: Dockerfile
    image: ansible-centos7
    container_name: ansible-centos7
    hostname: centos7
    working_dir: /home/ansible
  # ansible実行環境
  ansible-controller:
    build:
      context: ./controller
      dockerfile: Dockerfile
    image: ansible
    container_name: ansible-controller
    hostname: ansible
    tty: true
    volumes:
      - ./playbooks:/workspace
    working_dir: /workspace
